#!/bin/sh
if [ -x "/var/jb/usr/bin/uicache" ]; then
    /var/jb/usr/bin/uicache -p /var/jb/Applications/ZTech.app >/dev/null 2>&1 || /var/jb/usr/bin/uicache -a >/dev/null 2>&1
elif [ -x "/usr/bin/uicache" ]; then
    /usr/bin/uicache -p /Applications/ZTech.app >/dev/null 2>&1 || /usr/bin/uicache -a >/dev/null 2>&1
fi
exit 0
