#!/bin/sh
if [ -x "/var/jb/usr/bin/uicache" ] && [ -d "/var/jb/Applications/ZTech.app" ]; then
    /var/jb/usr/bin/uicache -p /var/jb/Applications/ZTech.app >/dev/null 2>&1 || true
    /var/jb/usr/bin/uicache -a >/dev/null 2>&1 || true
fi
if [ -x "/usr/bin/uicache" ] && [ -d "/Applications/ZTech.app" ]; then
    /usr/bin/uicache -p /Applications/ZTech.app >/dev/null 2>&1 || true
    /usr/bin/uicache -a >/dev/null 2>&1 || true
    /usr/bin/uicache >/dev/null 2>&1 || true
fi
exit 0
